# ==========================
# Spring Application
# ==========================

spring.application.name=QuantityMeasurementApp

# ==========================
# H2 Database Configuration
# ==========================

spring.datasource.url=jdbc:h2:mem:quantitydb

spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=

# ==========================
# JPA Configuration
# ==========================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==========================
# H2 Console
# ==========================

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console

# ==========================
# Logging
# ==========================

logging.level.root=INFO

logging.level.org.example=INFO

logging.file.name=logs/quantity-measurement.log

# ==========================
# Swagger
# ==========================

springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.operationsSorter=method