spring.application.name=QuantityMeasurement

server.port=8080

# ==========================
# H2 Database
# ==========================

spring.datasource.url=jdbc:h2:mem:quantitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Execute schema.sql and data.sql
spring.sql.init.mode=always

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# Google OAuth2
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ===============================
# JWT
# ===============================

jwt.secret=MySuperSecretKeyForQuantityMeasurementApplication2026
spring.config.import=optional:classpath:application-local.properties
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
jwt.expiration=86400000
spring.profiles.active=local
